### ISSUE TITLE
Clean UP & Dockerization eos7asg

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos7asg#6]

**Comment by HellenNamulinda** [comment]
Hello @GemmaTuron,
At first, the model was failing to fetch on my laptop, despite it working well on [Colab](https://colab.research.google.com/drive/1E9wCIwk-_pRpWCsNvd3VNz296Vqx0LG2?usp=sharing).
I checked the log ([eos7asg_fetch_repo.log](https://github.com/ersilia-os/eos7asg/files/11936886/eos7asg_fetch_repo.log))
 and java-jre was failing to install using the channel; [cyclus](https://anaconda.org/cyclus/java-jre/files).
```
Collecting package metadata (current_repodata.json): ...working... failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/hellenah/anaconda3/lib/python3.10/site-packages/conda/gateways/repodata/__init__.py", line 187, in conda_http_errors
        yield
      File "/home/hellenah/anaconda3/lib/python3.10/site-packages/conda/gateways/repodata/__init__.py", line 153, in repodata
        response.raise_for_status()
      File "/home/hellenah/anaconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
        raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://conda.anaconda.org/cyclus/linux-64/current_repodata.json
```
I tried some solutions which didn't work. From [this thread](https://github.com/conda/conda/issues/9948), an option that worked for similar situations was to downgrade conda.

I use the latest conda version, `23.5.0`. When I checked Colab([eos7asg_colab_fetch.log](https://github.com/ersilia-os/eos7asg/files/11936898/eos7asg_colab_fetch.log)) which was successful, it was using `4.12.0`.
Since [these files](https://anaconda.org/cyclus/java-jre/files) for java-jre were added 8years ago, I decided to downgrade conda.

After adding commands to first downgrade conda, install the packages and then update conda later seemed to work.
    - [eos7asg_fetch_repo_updated.log](https://github.com/ersilia-os/eos7asg/files/11936958/eos7asg_fetch_repo_updated.log)
```
RUN conda install -n base conda=4.12.0 
RUN conda install -c cyclus java-jre=8.45
RUN pip install padelpy==0.1.10
RUN conda update -n base -c defaults conda
```
I tested the model locally and it works.
    - Input file: [test.csv](https://github.com/ersilia-os/eos7asg/files/11937051/test.csv)
    - Output file: [eos7asg_test_output.csv](https://github.com/ersilia-os/eos7asg/files/11937057/eos7asg_test_output.csv)
```
🚀 Serving model eos7asg: padel

   URL: http://127.0.0.1:45841
   PID: 78358
   SRV: conda

👉 To run model:
   - run

💁 Information:
   - info
(ersilia) hellenah@hellenah-elitebook:~$ ersilia run -i "FC(F)Oc1ccc(-c2nnc3cncc(Oc4ccc5ccsc5c4)n23)cc1"
{
    "input": {
        "key": "MLBNXJTXHVBPEC-UHFFFAOYSA-N",
        "input": "FC(F)Oc1ccc(-c2nnc3cncc(Oc4ccc5ccsc5c4)n23)cc1",
        "text": "FC(F)Oc1ccc(-c2nnc3cncc(Oc4ccc5ccsc5c4)n23)cc1"
    },
    "output": {
        "descriptor": [
            8.255667804878042,
            163.52839133429237,
            123.42288183657432,
            1.7231502648338515,
            6.579268292682926,
            268.9508811728498,
            8.052925066666674,
            146.87015351166232,
...
```
I pushed the changes and created a [PR](https://github.com/ersilia-os/eos7asg/pull/7)

**Comment by HellenNamulinda** [comment]
Hello @GemmaTuron,
In regards to the [Colab error,](https://github.com/ersilia-os/eos7asg/issues/5#issuecomment-1619103449) I need your advice. [eos7asg_colab_fetch (1).log](https://github.com/ersilia-os/eos7asg/files/11943902/eos7asg_colab_fetch.1.log)

In an effort to ressolve the CLI error yesterday, it turned out that it's affecting colab. Since java-jre couldn't be installed with a higher version of conda, the solution is to lower the conda version before installing it. 
But I had made it that after installing the packages, conda is updated again.
```
RUN conda install -n base conda=4.12.0 
RUN conda install -c cyclus java-jre=8.45
RUN pip install padelpy==0.1.10
RUN conda update -n base -c defaults conda
```
However, from the log file, this is affecting the Colab version; `ModuleNotFoundError: No module named 'six'`. The update command happens to uninstall the said package. 
For downgrading; 
```
## Package Plan ##

  environment location: /usr/local

  added / updated specs:
    - conda=4.12.0


The following packages will be UPDATED:

  ca-certificates                      2022.3.29-h06a4308_1 --> 2023.05.30-h06a4308_0
  openssl                                 1.1.1n-h7f8727e_0 --> 1.1.1u-h7f8727e_0
```
But for updating;
```
## Package Plan ##

  environment location: /usr/local

  added / updated specs:
    - conda

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    cffi-1.15.1                |   py37h74dc2b5_0         227 KB
    cryptography-39.0.1        |   py37h9ce1e76_0         1.4 MB
    idna-3.4                   |   py37h06a4308_0          91 KB
    pycosat-0.6.4              |   py37h5eee18b_0          84 KB
    pyopenssl-23.0.0           |   py37h06a4308_0          96 KB
    requests-2.28.1            |   py37h06a4308_0          92 KB
    tqdm-4.64.1                |   py37h06a4308_0         126 KB
    ------------------------------------------------------------
                                           Total:         2.1 MB

The following packages will be REMOVED:

  colorama-0.4.4-pyhd3eb1b0_0
  conda-content-trust-0.1.1-pyhd3eb1b0_0
  pip-21.2.2-py37h06a4308_0
  six-1.16.0-pyhd3eb1b0_1
  wheel-0.37.1-pyhd3eb1b0_0
```
This isn't the same behavior on CLI. I did a git fetch from github to see the packages are being installed but it's not removing the said package. [eos7asg_fetch_github_updated.log](https://github.com/ersilia-os/eos7asg/files/11943955/eos7asg_fetch_github_updated.log)
```
## Package Plan ##

  environment location: /home/hellenah/anaconda3

  added / updated specs:
    - conda


The following packages will be UPDATED:

  conda                              4.12.0-py310h06a4308_0 --> 23.5.0-py310h06a4308_0
  ruamel_yaml                      0.15.100-py310h7f8727e_0 --> 0.17.21-py310h5eee18b_0
```
Should I remove the update command! but this will have put conda on people's machines at a very low version.
Or, should I add a command after to install six?
```
RUN conda install -c conda-forge six 
## or
RUN pip install six
```
**Refs**
https://stackoverflow.com/a/29968216
https://bobbyhadz.com/blog/python-no-module-named-six

**Comment by GemmaTuron** [comment]
Hi @HellenNamulinda 

I think adding the six install afterwards should work!

**Comment by HellenNamulinda** [comment]
Hello @GemmaTuron,
I did just that and the model still works well locally. 
I will check with Colab after merging this [PR](https://github.com/ersilia-os/eos7asg/pull/8).
